"""modified the exam schedule and the exams model

Revision ID: 7c329a664478
Revises: a5806e8a3bc8
Create Date: 2025-04-06 13:20:48.167477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c329a664478'
down_revision = 'a5806e8a3bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Exam_Schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examiner_id', sa.Integer(), sa.ForeignKey('Examiners.examiner_id', name='fk_exam_schedules_examiner_id_examiners'), nullable=True))

    with op.batch_alter_table('Exams', schema=None) as batch_op:
        # No need to explicitly drop the constraint
        batch_op.drop_column('examiner_id')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examiner_id', sa.Integer(), sa.ForeignKey('Examiners.examiner_id'), nullable=False))

    with op.batch_alter_table('Exam_Schedules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exam_schedules_examiner_id_examiners', type_='foreignkey')
        batch_op.drop_column('examiner_id')

    # ### end Alembic commands ###