"""fee status statement update

Revision ID: a5806e8a3bc8
Revises: 8380c1560fad
Create Date: 2025-04-06 11:54:47.679619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5806e8a3bc8'
down_revision = '8380c1560fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.alter_column('fee_cleared',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('CLEARED', 'NOT_CLEARED', name='feestatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Students', schema=None) as batch_op:
        batch_op.alter_column('fee_cleared',
               existing_type=sa.Enum('CLEARED', 'NOT_CLEARED', name='feestatus'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
